apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: skip-layers
  name: skip-layers
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: skip-layers:latest
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/mikecroft/leaky-secrets
    type: Git
    contextDir: skip-layers
  strategy:
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      from:
        kind: ImageStreamTag
        name: ubi-minimal:9.5
      env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: skip-layers-env
              key: TOKEN
      dockerfilePath:	skip-layers.Dockerfile        
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
  - type: ImageChange