apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    template.alpha.openshift.io/wait-for-ready: "true"
  labels:
    name: secret-mount-file
  name: secret-mount-file
  namespace: leak-test
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: secret-mount-file:latest
  runPolicy: Serial
  source:
    type: None
  strategy:
    customStrategy:
      env:
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            key: GITHUB_TOKEN
            name: secret-mount-file
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            key: AWS_ACCESS_KEY_ID
            name: secret-mount-file
      - name: AWS_SECRET_KEY
        valueFrom:
          secretKeyRef:
            key: AWS_SECRET_KEY
            name: secret-mount-file
      forcePull: true
      from:
        kind: ImageStreamTag
        name: custom-buildah-image:latest
    type: Custom
  successfulBuildsHistoryLimit: 5
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: secret-mount-file
---
kind: Secret
apiVersion: v1
metadata:
  name: secret-mount-file
stringData:
  AWS_ACCESS_KEY_ID: AKIA0123456789ABCDEF # notsecret
  AWS_SECRET_KEY: 12ASD34qwe56CXZ78tyH10Tna543VBokN85RHCas # notsecret
type: Opaque