apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: leaky-secrets
  name: leaky-secrets
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: leaky-secrets:latest
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/mikecroft/leaky-secrets
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: ubi-minimal:9.5
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
  - type: ImageChange