apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: secret-mount-env
spec:
  source:
    type: Dockerfile
    dockerfile: |-
      FROM registry.redhat.io/ubi9/ubi-minimal:9.5

      RUN microdnf install -y python

      RUN --mount=type=secret,id=AWS_ACCESS_KEY_ID \
          --mount=type=secret,id=AWS_SECRET_KEY \
          echo "AWS_ACCESS_KEY_ID=$(cat /run/secrets/AWS_ACCESS_KEY_ID)" && \
          echo "AWS_SECRET_KEY=$(cat /run/secrets/AWS_SECRET_KEY)"


      ENTRYPOINT [ "python" ]

      CMD [ "-m", "http.server", "8080" ]
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: 'registry.redhat.io/ubi9/ubi-minimal:9.5'
      env:
        - name: AWS_ACCESS_KEY_ID
          value: AKIA0123456789ABCDEF # notsecret
        - name: AWS_SECRET_KEY
          value: 12ASD34qwe56CXZ78tyH10Tna543VBokN85RHCas # notsecret
  output:
    to:
      kind: ImageStreamTag
      name: 'secret-mount-env:latest'
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: secret-mount-env