kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: secret-mount
  labels:
    name: secret-mount
  annotations:
    template.alpha.openshift.io/wait-for-ready: 'true'
spec:
  strategy:
    type: Custom
    customStrategy:
      forcePull: true
      from:
        kind: ImageStreamTag
        name: custom-buildah-image:latest
        namespace: leak-test
  output:
    to:
      kind: ImageStreamTag
      name: secret-mount:latest